//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUI_EF_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Emp
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpSex { get; set; }
        public int EmpAge { get; set; }
        public System.DateTime EmpBirthday { get; set; }
        public int DeptId { get; set; }
    
        public virtual T_Dept T_Dept { get; set; }
    }
}
